### ISSUE TITLE
install node.js after extension installed makes it blank page

### ISSUE THREAD

**Issue by adrianzhang** [JudiniLabs/code-gpt-docs#292]
I install CodeGPT extension in VS Code 1.19, and then it gives me an error and guide me through troubleshooting page, where I found I have to install Node.js first on my MacOS Monterey. 

Once installed node.js 20.0, the extension still give me a blank page. 

I'v tried to disable and enable again, it prompt to login, and then I paste the address to Chrome and logged in. Still, the extension shows a blank.

**Comment by Adel242** [comment]
This was corrected in the latest version of Code GPT, make sure you are on the version 3.4.01

**Comment by PilarHidalgo** [comment]
@adrianzhang, you can also follow these steps:
1: Uninstall the extension
2: CleanCachee for macOS:
 - Could you ensure VS Code is closed before you clean the Cache?
 - Use Terminal to navigate through your file system.
 - Go to Library/Caches/com. microsoft.VSCode. 
 - Delete the Cache there
 - Go to Library/Application Support/Code.
 -  Delete the Cache there
 - Also, you can delete the Cache, extension cache, and CachedData folders.
 3: Be aware of the VSCode and Node versions
 4: Install the CodeGPT extension again

Please let us know how is going

**Comment by adrianzhang** [comment]
> @adrianzhang, you can also follow these steps: 1: Uninstall the extension 2: CleanCachee for macOS:@adrianzhang，您还可以按照以下步骤操作： 1：卸载扩展 2：适用于 macOS 的 CleanCachee：
> 
> * Could you ensure VS Code is closed before you clean the Cache?您能否确保在清理缓存之前关闭 VS Code？
> * Use Terminal to navigate through your file system.使用终端在文件系统中导航。
> * Go to Library/Caches/com. microsoft.VSCode.转到 Library/Caches/com. microsoft。VSCode 的 URL 代码。
> * Delete the Cache there删除那里的缓存
> * Go to Library/Application Support/Code.转到 Library/Application Support/Code。
> * Delete the Cache there删除那里的缓存
> * Also, you can delete the Cache, extension cache, and CachedData folders.
>   3: Be aware of the VSCode and Node versions
>   4: Install the CodeGPT extension again此外，您还可以删除 Cache、extension cache 和 CachedData 文件夹。
>   3：注意 VSCode 和 Node 版本
>   4：再次安装 CodeGPT 扩展
> 
> Please let us know how is going请告诉我们进展如何

Thanks.

I'v used other plugins for using local AI. Recently it works. However, there is a prompt says login for xx days free or something else I'v totally forgot, so I delete it completely. What I want is a plugin to access ollama on anothe computer in the same lan in order to use offline editor, api and models, for code safety. 

Sorry I'm not able to continue test, but this issue is fixed and can be closed.
