### ISSUE TITLE
404 The model `gpt-4o` does not exist or you do not have access to it. in vs code codegpt extension

### ISSUE THREAD

**Issue by RohitRam9701** [JudiniLabs/code-gpt-docs#298]
I added api key 🗝 in codegpt but it is showing "404 The model `gpt-4o` does not exist or you do not have access to it."  or, 
"429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors"

useless Extension

**Comment by Adel242** [comment]
Hello @RohitRam9701, you need to verify your OpenAI account with OpenAI to see if it has credits.
