### ISSUE TITLE
Unable to connect to the extension services

### ISSUE THREAD

**Issue by mfgering** [JudiniLabs/code-gpt-docs#303]
vscode extension fails to initialize with "Unable to connect to the extension services" and the app port 54112 seems to be the problem.

While the extension complains, I can open another window and listen on port 54112 (using 'nc -l localhost 54112).

If I relaunch vscode while keeping nc listening on 54112, I see this POSTed to that port:

```
POST /54113/api/settings HTTP/1.1
host: localhost:54112
connection: keep-alive
Content-Type: application/json
accept: */*
accept-language: *
sec-fetch-mode: cors
user-agent: node
accept-encoding: gzip, deflate
content-length: 433

{"distinctId":"50331a80-52b7-48ac-afce-f8231d7e139b","globalState":{"codeGPTUserId":"50331a80-52b7-48ac-afce-f8231d7e139b","config":{},"autoComplete":{"enabled":true,"provider":"Ollama","model":"llama3:instruct","maxTokens":128,"suggestionDelay":600}},"config":{"apiKey":"OpenAI","query":{"language":"English"},"Autocomplete":{"enabled":true,"provider":"Ollama - llama3:instruct","maxTokens":128,"suggestionDelay":600}},"secrets":{}}
```

I'm confused about why codegpt can't use port 54112. This happens on two different systems:

OS: Opensuse tumbleweed (up-to-date)
Vscode: 1.90.2
Vscode Node: 20.9.0

Any help is much appreciated!

**Comment by mfgering** [comment]
What I discovered:
- the HOSTNAME environment variable was set ("dt1" in my case)
- the codegpt extension caused a next-server process to get started on my external interface, 192.168.1.40 and listening to port 54112
- the codegpt was looking to connect to 0.0.0.0:54112 instead of 192.168.1.40:54112

Unsatisfying fix: unset HOSTNAME before launching code. This allows codegpt to initialize and connect to next-server on 0.0.0.0:54112

**Comment by mfgering** [comment]
Conclusion: Vscode will launch codegpt server (next-server) on port 54211 for an interface for hostname in the HOSTNAME environment variable. If this is an external interface (not 0.0.0.0 but something like 192.168.1.40), then codegpt won't be able to connect to it.

Solution: unset HOSTNAME before launching code. This causes vscode to launch codegpt's next-server on 0.0.0.0:54112 and that works.

**Comment by alessandrocornacchia** [comment]
How can I systematically apply this fix when working on a remote SSH VSCode instance?
