### ISSUE TITLE
There is no "CodeGPT: Set API KEY" option in cmd-shift-p menu

### ISSUE THREAD

**Issue by tandav** [JudiniLabs/code-gpt-docs#311]
<img width="993" alt="image" src="https://github.com/user-attachments/assets/8a5da7f2-ed68-426a-939b-59d98fca97ac">

<img width="615" alt="image" src="https://github.com/user-attachments/assets/67a7a9ad-4900-43fa-b5d1-d0490f24c7bf">

**Comment by davila7** [comment]
This action is no longer necessary. To add the API Key, simply select each provider and then click 'Set Connection'.

This text will no longer be displayed in the next version.
