### ISSUE TITLE
Cannot initialize interface in windows 11

### ISSUE THREAD

**Issue by qiqing-bnu** [JudiniLabs/code-gpt-docs#316]
I installed this plugin in VS-code on Windows 11, and then running it, it always stays in a blank screen without any display. Does this plugin need VPN in China when it fist launch？

**Comment by PilarHidalgo** [comment]
Hi @qiqing-bnu , Here are some steps you can take to resolve this:
- Update VSCode to version 1.85 or more.
- Ensure you have Node version 20.0 or more installed.
- Make sure the CodeGPT extension version 3.2.5 or higher is running.
- Delete cache memory: Press Ctrl + Shift + P, type command "Clear Editor History", Press Enter
- shut vscode and install CodeGPT again

**Comment by qiqing-bnu** [comment]
Thank you, today is OK. I do nothing, it seems to have fixed itself.
