### ISSUE TITLE
code completion with ollama not working (500 on api/generate)

### ISSUE THREAD

**Issue by Albee24** [JudiniLabs/code-gpt-docs#321]
I am able to chat just fine with my llama3:instruct model just fine, but when I try to use the autocomplete, it is always failing with a 500 status on the api/generate call.
<img width="1182" alt="Screenshot 2024-07-27 at 12 00 09 AM" src="https://github.com/user-attachments/assets/9c28712f-2880-4836-812a-58c48cbbd7e1">

MacOS version: Sonoma 14.5
ollama version: 0.3.0
model: llama3:instruct
CodeGPT version: 3.4.47
VS Code version: 1.91.1

**Comment by Vokturz** [comment]
llama3:instruct has no support to autocomplete. You can use codellama instead.
