### ISSUE TITLE
CodeGPT "Unable to connect to the extension services"

### ISSUE THREAD

**Issue by nir-arad** [JudiniLabs/code-gpt-docs#324]
I was able to use CodeGPT vscode extension before.

Today, the extension refuses to load with the message "Unable to connect to the extension services".
vscode version 1.91.1
vscode node version 20.9.0
netstat for port 54112 returns empty

I tried all of the following:
- Switched from RemoteSSH to WSL to Windows local
- Disconnected from VPN
- Reboot
- Reinstalled the extension a couple of times.

None of the above solved the issue.

Please advise.

**Comment by nir-arad** [comment]
The issue resolved with no action from my side.

**Comment by a472691** [comment]
me too

**Comment by TangYu626** [comment]
Hello, I have the same problem and I don't know how to solve it.

**Comment by iamktulhu** [comment]
the same

![Image](https://github.com/user-attachments/assets/3f9ebbc1-db5b-4173-b93a-63744125d6a3)

**Comment by astrohart** [comment]
Me too

**Comment by 00guai** [comment]
me too
