### ISSUE TITLE
CodeGPT's answers often contain incorrect codes

### ISSUE THREAD

**Issue by ZymBeCool** [JudiniLabs/code-gpt-docs#346]
Recently, CodeGPT's answers often contain incorrect codes:
1) Indent error（Figure 1）
2) The correct statement appears in the wrong place（Figure 2）
It seems that these problems are not common in the past time.
![QQ_1722998448538](https://github.com/user-attachments/assets/daba1f9d-c72b-4fa8-9f0a-2731b0b31dfa)
![QQ_1722998501623](https://github.com/user-attachments/assets/8c9766ea-6e22-458e-949a-b2b7d21a3b5b)

**Comment by PilarHidalgo** [comment]
Hi! Yes, we are aware of this issue and are working on it. Thanks for reporting it.
