### ISSUE TITLE
SSO login for Azure OpenAI

### ISSUE THREAD

**Issue by wasawatpeng** [JudiniLabs/code-gpt-docs#351]
Now we need to get API Key to login to Azure Open AI. Can we use SSO as the login authentication for Azure? The reason is my enterprise only provide the permission to use Azure Open AI service in Azure Portal, but cannot get the API Key.

**Comment by PilarHidalgo** [comment]
Hi @wasawatpeng,  the API Key is the only way to connect with your provider, so you need to get it to use it in CodeGPT
