### ISSUE TITLE
Code auto-completion with Ollama stopped working

### ISSUE THREAD

**Issue by joeattardi** [JudiniLabs/code-gpt-docs#369]
It's been working fine the past few days but all of a sudden it stopped working.

No completions.

When I go into CodeGPT settings, and select my AI Model (codellama:code), it shows a little spinner for a few seconds then nothing happens. Nothing in the logs.

![Screen Recording 2024-09-20 at 1 40 29 PM](https://github.com/user-attachments/assets/b3221ddf-c1ac-40f6-9659-adce4faac34b)

**Comment by minkesh** [comment]
Facing the same issue, please check

**Comment by davila7** [comment]
It's already fixed in version 3.5.80

Thanks for letting us know :)
<img width="469" alt="Screenshot 2024-09-22 at 14 31 41" src="https://github.com/user-attachments/assets/ea7b0506-463a-4e41-9fe7-778c27571201">

**Comment by joeattardi** [comment]
Yup it works again! Thanks for the quick fix!
