### ISSUE TITLE
how to edit large files?

### ISSUE THREAD

**Issue by AndreySocium** [JudiniLabs/code-gpt-docs#375]
I use a plugin for VS Code. My file is 672 lines. I write a prompt, but the page is cut off and at the bottom of chat I see this "...542 lines truncated". The responses from gpt also come cut off. How can I edit the entire document?
look at the screenshot pls. In preferences i can't change anything.
![codegpt](https://github.com/user-attachments/assets/a068d746-08ba-4bad-b324-fb91376105a2)
<img width="1496" alt="Снимок экрана 2024-10-08 в 16 22 59" src="https://github.com/user-attachments/assets/0a6ad6a6-4ece-4c82-9e4d-57e6689893ea">

**Comment by PilarHidalgo** [comment]
Hi @AndreySocium For the moment, it is not possible to temporarily increase the row size. However, you could split the file for now, and the context window will allow you to make a continuous query.
