### ISSUE TITLE
Implement a feature that visually distinguishes suggested code changes from existing code, similar to Cursor's functionality

### ISSUE THREAD

**Issue by osadchy** [JudiniLabs/code-gpt-docs#377]
- New or added code: Highlighted in green
- Removed or replaced code: Highlighted in red (or struck through)
- Unchanged code: Remain in default color

**Comment by PilarHidalgo** [comment]
Hi @osadchy! thank you for these suggestions. I will add them to our roadmap, and our team will evaluate them. Also, if you have more suggestions, please let them here:  https://codegpt.canny.io/
