### ISSUE TITLE
Feature: Add option to add Azure OpenAI for AI code auto-completion

### ISSUE THREAD

**Issue by gunsto** [JudiniLabs/code-gpt-docs#378]
Hi, as already requested in [this feature request](https://github.com/JudiniLabs/code-gpt-docs/issues/197) (which cannot be commented anymore), I would like to ask to enable Azure OpenAI also for the code auto-completion, if it is technically possible.
The other feature request was closed to early, because it just describes the way to integrate Azure OpenAI as regular chat and not for auto-completion, as can be seen in the dropdown menu for the LLM providers.
![drop down for LLM](https://github.com/user-attachments/assets/652d339b-f667-4537-a136-030f00bdfc7f)
![drop down for LLM](https://github.com/user-attachments/assets/2c9b0c25-6c68-4a7d-9f05-894226293fea)

**Comment by PilarHidalgo** [comment]
At this time, we have decided not to include models like Azure OpenAI due to the quality of the auto-completion process. However, the models featured in the extension are specially designed for code generation. We invite you to try them out.
