### ISSUE TITLE
Problem with running ChatGPT in CodeGPT

### ISSUE THREAD

**Issue by marekmitonski** [JudiniLabs/code-gpt-docs#382]
I have a problem running ChatGPT in the CodeGPT plugin. I’m getting an error as shown in the attached image. I have the paid version of ChatGPT.

![image](https://github.com/user-attachments/assets/0b0774c1-8eb4-41ce-a960-dca8b9eb4167)

![image](https://github.com/user-attachments/assets/fac5d9cc-e5dc-4ef0-8ab4-75354c308e37)

**Comment by GeraltRivskiy** [comment]
Double this problem, I have the same error about a week already

**Comment by marekmitonski** [comment]
"I solved my issue... It turned out that simply purchasing a ChatGPT subscription for $20 is only part of the solution. You also need to buy API access, which is billed separately based on tokens...

On the other hand, CodeGPT could display clearer error messages."

**Comment by GeraltRivskiy** [comment]
> "I solved my issue... It turned out that simply purchasing a ChatGPT subscription for $20 is only part of the solution. You also need to buy API access, which is billed separately based on tokens...
> 
> On the other hand, CodeGPT could display clearer error messages."

Thats odd. I used my employer's account and I doubt that he paid for api access. Well, maybe I dont know something, anyway, thx for advice

**Comment by PilarHidalgo** [comment]
@marekmitonski, thanks for the advice, I will communicate this to my team
