### ISSUE TITLE
extension license 404

### ISSUE THREAD

**Issue by GitMensch** [JudiniLabs/code-gpt-docs#383]
As noted in #200 the license information about the extension https://marketplace.visualstudio.com/items/DanielSanMedium.dscodegpt/license links to https://marketplace.visualstudio.com/items/DanielSanMedium.dscodegpt/license which results in an HTTP404.

Please fix that (and possibly change the referenced issue from closed-fixed to closed-wontfix).

**Comment by GitMensch** [comment]
@CammRios maybe you can have a look at this (or file an "upstream" issue / ticket)?

**Comment by PilarHidalgo** [comment]
@GitMensch , we are working on this. Thanks for the feedback

**Comment by GitMensch** [comment]
Hm, the workflow I know is to either close issues as soon as something is somehow available for check/tests or as soon as it is "delivered" - in this case both seem identical. Closing as soon as things are worked on (or even planned to be) is a new workflow to me.

... of course you are free to close all issues but this one ... is actually still open.
