### ISSUE TITLE
Autocomplete in VScode is not working

### ISSUE THREAD

**Issue by markosci89** [JudiniLabs/code-gpt-docs#390]
I just installed the CODEGPT extension and enabled codellama:latest, but autocomplete doesn't work in any type of file.

I've tried with several file extensions, such as JS, PHP, HTML... and still nothing. When I check the configuration, the provider and model show me that is connected.

![image](https://github.com/user-attachments/assets/f7c4257f-112a-45b9-95bb-d2fdd16699a8)

**Comment by PilarHidalgo** [comment]
Hi!, remember that you must keep running local models to use them with auto-complete. Please follow the instructions here:https://docs.codegpt.co/docs/tutorial-ai-providers/ollama

**Comment by PilarHidalgo** [comment]
@carlospaiva Hey there! We've fixed the issue in our Pre-Release version, please go to the extensions section and click on "Switch to Pre-Release version"
